Make it possible to not check commit messages format.
This is needed to avoid CI issues with upstream commit messages.

diff --git a/.gitlab/ci/bases.yml b/.gitlab/ci/bases.yml
--- a/.gitlab/ci/bases.yml
+++ b/.gitlab/ci/bases.yml
@@ -117,14 +117,17 @@ variables:
       fi
       echo "MR #${CI_MERGE_REQUEST_IID} (detached from ${GITLAB_USER_LOGIN}/${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}) is rebased."
     - |
-      msg "Iteratively validate the message format of the commits within MR #${CI_MERGE_REQUEST_IID}..."
-      for c in `git rev-list kaios/${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}..FETCH_HEAD --reverse`; do
-        cmsg="$(git show ${c} -q --format=%s)"
-        if ! [[ ${cmsg} =~ ${COMMIT_MESSAGE_PATTERN} ]]; then
-          die "Commit message format error: ${cmsg}"
-        fi
-        echo "commit message of ${c} validated."
-      done
+      echo "Title is $CI_MERGE_REQUEST_TITLE"
+      if ! [[ "$CI_MERGE_REQUEST_TITLE" =~ 'upstream-merge' ]]; then
+        msg "Iteratively validate the message format of the commits within MR #${CI_MERGE_REQUEST_IID}..."
+        for c in `git rev-list kaios/${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}..FETCH_HEAD --reverse`; do
+          cmsg="$(git show ${c} -q --format=%s)"
+          if ! [[ ${cmsg} =~ ${COMMIT_MESSAGE_PATTERN} ]]; then
+            die "Commit message format error: ${cmsg}"
+          fi
+          echo "commit message of ${c} validated."
+        done
+      fi
 
 .changed_files_validation:
   image: ${CI_REGISTRY}/releng/ci-util/dockerhub-mirror/python:3.8.6
